# **PROCESSO DECISÓRIO MULTICRITÉRIO**
Gabriel Przytocki; Allan Braun; Valdemar Ceccon <br>
Maio, 2022

In [47]:
# importações de bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine

# 1. **INTRODUÇÃO**

A tomada de decisão é um problema recorrente em diversos contextos, sejam empresarias, industriais ou cotidianos. Ao tomar decisões, usualmente utilizam-se critérios subjetivos que serão ponderados pelo indivíduo, usualmente um especialista em uma determinada área. Também tem o caso da decisão ser tomada por um grupo de pessoas, em acordo, que discutem acerca de diferentes pontos de vista e aspectos de cada escolha. Ao final, escolhe-se uma opção em detrimento das demais; invariavelmente, em uma escolha, toma-se a decisão baseada em critérios.

# 2. **EMPRESA E PROBLEMA DE DECISÃO**
## 2.1. Descrição da Empresa
A empresa "**Campos de Dionísio**" produz vinhos em larga escala, comercializando-os no mundo todo. Trata-se de uma empresa tradicional, que produz apenas três tipos de vinhos, cujos campos localizam-se no leste europeu. A empresa passou os últimos meses investindo em engenheiros de dados, construindo um fluxo automático que alimenta um banco de informações a respeito de características dos três tipos de vinho, ao longo do processo de produção. A empresa também investiu em profissionais da área estatística, para analisar os dados recém registrados. Seguindo as tendências da era da informação, a empresa tradicional decidiu não só contratar engenheiros e cientistas, mas também investiu em tecnologia no seu processo de produção, passando um ano com projetos de desenvolvimento de *software*, até finalizar a versão inicial de um sistema que gerencia todo o processo, minimizando a mão de obra necessária na produção dos vinhos.

## 2.2. Descrição do Problema de Decisão
Jurandir é um gerente de um dos campos de vinícula, e preocupa-se diariamente com a qualidade do produto, dos processos e da satisfação final do cliente. Certo dia recebeu uma demanda de um de seus melhores clientes, Adão, do qual estava em dúvida acerca de dois vinhos. Adão era um entusiasta do ramo, e recentemente havia contraído uma certa doença rara que o limitava acerca do consumo de suas bebidas preferidas, cujo nome não importa para o problema em questão. Esse cliente possuía um poder aquisitivo elevado, e contratou um profissional da saúde, que junto de Jurandir olharam para os dados quantitativos dos dois vinhos em questão, ponderando acerca das quantidades de cada atributo em cada uma das amostras. Ao final, os dois profissionais, em conjunto, elaboraram certas regras que minimizavam possíveis impactos do consumo dos vinhos para Adão, ou seja, definiram quais quantidades representavam melhores ou piores impactos em sua saúde. O problema de decisão é: agora que os profissionais já definiram quais atributos impactam mais ou menos em relação a Adão, como tomar esse decisão?

## 2.3. Critérios de Decisão
* **Critério 1**: `alcohol` Quantidade de álcool presente no vinho
* **Critério 2**: `malic_acid` Quantidade de ácido málico presente no vinho
* **Critério 3**: `color_intensity` Intensidade da cor do vinho
* **Critério 4**: `magnesium` Quantidade de magnésio presente no vinho

## 2.4. Alternativas de Decisão
Existem dois vinhos distintos, dos quais apenas um será escoilhido (vinho $A$ e vinho $B$).

Abaixo, carrega-se a base de dados completa dos vinhos de Jurandir, com diversos atributos.

In [ ]:
data = load_wine()
df = pd.DataFrame(data=data['data'], columns=data['feature_names'])
df['target'] = data['target']

print(df.shape)
df.head()

(178, 14)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

Escolhe-se apenas dois vinhos, as duas alternativas

In [ ]:
df.sample(2)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
117,12.42,1.61,2.19,22.5,108.0,2.0,2.09,0.34,1.61,2.06,1.06,2.96,345.0,1
20,14.06,1.63,2.28,16.0,126.0,3.0,3.17,0.24,2.10,5.65,1.09,3.71,780.0,0

Como Adão possui problemas apenas com alguns dos compostos dos vinhos, selecionamos apenas os atributos de nosso interesse

In [ ]:
# alternativas de escolha
wines = df.loc[[117,20]][['alcohol', 'malic_acid', 'color_intensity', 'magnesium']]
wines

     alcohol  malic_acid  color_intensity  magnesium
117    12.42        1.61             2.06      108.0
20     14.06        1.63             5.65      126.0

# 3. **TOMADA DE DECISÃO COM MULTICRITÉRIOS**

## 3.1. Considerações Gerais
A tomada de decisão com multicritérios busca sistematizar o processo de escolha; em outras palavras, ao invés de tomar uma decisão baseada exclusivamente em percepções subjetivas, ainda que baseada em dados quantitativos, ou então em conjunto com outras pessoas (tais como especialistas e afins), separamos em diferentes critérios que impactam as decisões. Esse método permite observar a situação em diferentes âmbitos, não sendo completamente objetivo, pois a importância de cada critério é atribuida pelo indivíduo, porém tenta minimizar erros e confusões oriundas da completa subjetividade.

## 3.2. *Analytic Hierarchy Process* (`AHP`)

Em muitos problemas do mundo real, precisamos tomar uma decisão, ou seja, precisamos ponderar acerca de diferentes opções e escolher uma em detrimento das demais. Nesse sentido, como elaborar uma maneira lógica de tomar essa decisão? Mais ainda, como efetuar essa decisão de maneira sistemática, ponderando os diversos critérios acerca de cada opção? Nesse contexto entra o *Analytic Hierarchy Process* (**AHP**), um processo, ou método de tomada de decisão. Listamos as opções de escolha (diferentes produtos, métodos, processos, entre outros) e definimos diferentes critérios a serem levados em consideração, em seguida atribuimos diferentes importâncias para cada critério; posteriormente, avaliamos a importância de cada opção em detrimento das demais, e repetimos esse processo para todos os critérios definidos. Em outras palavras, avaliamos as diferentes opções à luz de diferentes critérios. Após definir as respectivas importâncias, elaboramos diferentes matrizes, que serão processadas, normalizadas e, por fim, multiplicadas. Ao fim desse processo, obtemos um percentual referente a cada opção que temos, quase como um *score* respectivo a cada possibilidade de escolha, ponderada pelos diferentes critérios; ao final, a opção que tiver o maior percentual, é a opção a ser escolhida, ou seja, a opção que mais reflete, na média, os critérios definidos.

## 3.3. Algoritmo para o `AHP`

Segue abaixo o algoritmo para o AHP, passo a passo:

---
##### **PROCEDIMENTO** *Analytic Hierarchy Process*:
---
<ul>
<li> 1. Para cada um dos critérios $C_i$ definidos: </li>
     <ul>
        <li> 
        1.1. Definir a matriz $M_{o,o} = O \times O$ de <i>opções x opções</i>, relativa à importância de cada item em relação a todos os demais, de acordo com o critério $C_i$ em questão;
        </li>
        <li> 1.2. Normalizar a matriz de <i> opções x opções </i> obtida, somando cada coluna $i$ e dividindo os elementos de cada coluna $M_{i,j}$ pela soma obtida;
        </li>
        <li> 1.3 Obter a média de cada linha da matriz, ou seja, de cada opção referente ao critério $C_i$;
     </ul>
<li> 2. Montar uma matriz $M_{o,c} = O \times C$ de <i> opções x critérios</i>, com a junção das médias obtidas referente a cada critério $C_i$;
<li> 3. Montar uma matriz $M_{c,c} = C \times C$ de <i> critérios x critérios</i>, avaliando a importância de cada critério em detrimento dos demais; </li>
<li> 4. Normalizar a matriz $M_{c,c}$ de maneira análoga ao item 1.2;</li>
<li> 5. Realizar o produto da matriz $M_{c,c}$ normalizada com $M_{o,c}$, referente às médias obtidas de cada opção frente a cada critério ($M_{c,c} \times M_{o,c}$
</ul>

---

### 3.3.1 Escala *Saaty* para importância dos critérios
```
1: Igual importância
2: Igual importância
3: Fraca importância
4: Fraca importância
5: Forte importância
6: Forte importância
7: Muito forte importância
8: Muito forte importância
9: Extremamente importante
```

## 3.4. Exemplo de aplicação
Segue abaixo um exemplo, passo a passo, de aplicação do AHP, utilizando a classe em `Python` criada. O exemplo é sobre a escolha de um entre dois empregos, baseado em quatro critérios distintos.

In [1]:
# importando a classe AHP
from ahp.ahp import AHP

### **Critério 1**: Salário

In [5]:
c1_salario_jobs = [[1, 1/6],
                   [6, 1]]

df = AHP.pretty_print_matrix(c1_salario_jobs, 
                             key='Emprego', 
                             title='Critério 1: Salário')
df.head()

         Critério 1: Salário
                    Emprego1  Emprego2
Emprego1                   1  0.166667
Emprego2                   6  1.000000

### **Critério 2**: Oportunidade profissional

In [23]:
c2_oportunidade_jobs = [[1, 8],
                        [1/8, 1]]

df = AHP.pretty_print_matrix(c2_oportunidade_jobs, 
                             key='Emprego', 
                             title='Critério 2: Oportunidade profissional')
df.head()

         Critério 2: Oportunidade profissional
                                      Emprego1 Emprego2
Emprego1                                 1.000        8
Emprego2                                 0.125        1

### **Critério 3**: Localização

In [24]:
c3_local_jobs = [[1, 1/5],
                 [5, 1]]

df = AHP.pretty_print_matrix(c3_local_jobs, 
                             key='Emprego', 
                             title='Critério 3: Localização')
df.head()

         Critério 3: Localização
                        Emprego1 Emprego2
Emprego1                       1      0.2
Emprego2                       5      1.0

### **Critério 4**: Custo de vida

In [25]:
c4_custo_jobs = [[1, 4],
                 [1/4, 1]]

df = AHP.pretty_print_matrix(c4_custo_jobs, 
                             key='Emprego', 
                             title='Critério 4: Custo de vida')
df.head()

         Critério 4: Custo de vida
                          Emprego1 Emprego2
Emprego1                      1.00        4
Emprego2                      0.25        1

### *Critérios x Critérios*

In [10]:
# quais critérios são mais importantes?
criteria_matrix = [[1, 1/7, 1/3, 1/2],
                   [7, 1, 5, 5],
                   [3, 1/5, 1, 3],
                   [2, 1/5, 1/3, 1]]
            
df = AHP.pretty_print_matrix(criteria_matrix, 
                             key='C', 
                             title='Critério x Critério')
df.head()

   Critério x Critério
                    C1        C2        C3   C4
C1                   1  0.142857  0.333333  0.5
C2                   7  1.000000  5.000000  5.0
C3                   3  0.200000  1.000000  3.0
C4                   2  0.200000  0.333333  1.0

In [13]:
# agrupando os dados de entrada
data = [c1_salario_jobs,
        c2_oportunidade_jobs,
        c3_local_jobs,
        c4_custo_jobs,
        criteria_matrix]

Instanciando o modelo e obtendo uma decisão acerca de qual emprego escolher

In [14]:
# instanciando o modelo
ahp = AHP()

# alimentando o modelo com as matrizes de preferência
ahp.fit(data)

# classificando
ahp.classificate()

array([[0.67920862],
       [0.32079138]])

Obtemos 67% para o **emprego 1**, portanto essa é a escolha final.

### Visualizando as matrizes ao longo do processo, até a decisão final

#### Matrizes normalizadas

In [22]:
# critério 1
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][0],
    key='Emprego', 
    title='Critério 1: Salário'
)

df.head()

         Critério 1: Salário
                    Emprego1  Emprego2
Emprego1            0.142857  0.142857
Emprego2            0.857143  0.857143

In [26]:
# critério 2
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][1], 
    key='Emprego', 
    title='Critério 2: Oportunidade profissional'
)

df.head()

         Critério 2: Oportunidade profissional
                                      Emprego1  Emprego2
Emprego1                              0.888889  0.888889
Emprego2                              0.111111  0.111111

In [27]:
# critério 3
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][2], 
    key='Emprego', 
    title='Critério 3: Localização'
)

df.head()

         Critério 3: Localização
                        Emprego1  Emprego2
Emprego1                0.166667  0.166667
Emprego2                0.833333  0.833333

In [28]:
# critério 4
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][3], 
    key='Emprego', 
    title='Critério 4: Custo de vida'
)

df.head()

         Critério 4: Custo de vida
                          Emprego1 Emprego2
Emprego1                       0.8      0.8
Emprego2                       0.2      0.2

#### Matriz de preferências (de empregos por critérios)

In [53]:
# matriz de preferência: empregos x critérios
df = pd.DataFrame(
    data=ahp.data['classification_matrices_preference'],
    index=['Emprego 1', 'Emprego 2'],
    columns=[f'C{i}' for i in range(1,len(data))]
)

df.head()

                 C1        C2        C3   C4
Emprego 1  0.142857  0.888889  0.166667  0.8
Emprego 2  0.857143  0.111111  0.833333  0.2

#### Matriz com médias de cada critério

In [54]:
# médias de cada critério
df = pd.DataFrame(
    data=ahp.data['criteria_matrix_mean'][0],
    index=[f'C{i}' for i in range(1,len(data))],
    columns=['Média']
)

df.head()

       Média
C1  0.068037
C2  0.615731
C3  0.206547
C4  0.109685

#### Decisão final: Produto de matrizes (*matriz de preferências* $\times$ *matriz de médias de critérios*)

In [55]:
# multiplicação das duas matrizes acima
# matriz de preferência x matriz de médias de critérios
np.dot(
    ahp.data['classification_matrices_preference'],
    np.reshape(ahp.data['criteria_matrix_mean'],(-1,1))
)

array([[0.67920862],
       [0.32079138]])

# 4. **MODELO MULTICRITÉRIO DE DECISÃO**

## 4.1. `AHP` para Hierarquização das Alternativas de Decisão
### 4.1.1. **1º Nível**: *Critérios de Decisão*
Segue abaixo as importâncias (utilizando a escala *Saaty*) dos vinhos $A$ em relação ao vinho $B$, à luz de cada um dos critérios. O especialista, juntamente de Jurandir, transcreveram suas decisões e ponderação para a escala utilizada no AHP.

In [75]:
# critério 1
c1_alcohol = [[1, 1/5],
              [5, 1]]

# critério 2
c2_malic_acid = [[1, 1],
                 [1, 1]]

# critério 3
c3_color_intensity = [[1, 1/7],
                      [7, 1]]

# critério 4
c4_magnesium = [[1, 6],
                [1/6, 1]]

Transcrevendo os dados acima, a matriz de critérios 1 afirma que o vinho $B$ possui forte importância em relação ao vinho $A$, considerando-se a quantidade de álcool, pois é potencialmente menos prejudicial. Em relação ao ácido málico, ambos vinhos possuem mesma importância (ambos não são prejududiciais). Acerca da intensidade da cor do vinho, o vinho $B$ é muito mais importante (menos prejudicial). Por fim, em relação ao magnésio, o vinho $A$ possui maior importância.

In [76]:
# matriz de critérios x critérios
criteria_matrix = [[1, 1/7, 1/3, 1/2],
                   [7, 1, 5, 5],
                   [3, 1/5, 1, 3],
                   [2, 1/5, 1/3, 1]]

Acima, segue a relevância de cada um dos compostos do vinho, em relação à doença de Adão.

In [77]:
# agrupando os dados
data = [c1_alcohol,
        c2_malic_acid,
        c3_color_intensity,
        c4_magnesium,
        criteria_matrix]

### 4.1.2 Utilizando o modelo

In [78]:
# instanciando o modelo
ahp = AHP()

# alimentando o modelo com os dados
ahp.fit(data)

# classificando
ahp.classificate()

array([[0.43903903],
       [0.56096097]])

Obtemos 56% para o **vinho $B$**, portanto essa é a escolha final.

## 4.2. Análise dos Resultados
### Visualizando as matrizes ao longo do processo, até a decisão final
Como análise dos resultados, vamos construir o passo a passo até a obtenção da decisão final, ou seja, exibir as matrizes intermediárias obtidas durante o processo, até o resultado final (decisão).

#### Matrizes normalizadas

In [79]:
# critério 1
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][0],
    key='Vinho', 
    title='Critério 1: Alcohol'
)

df.head()

       Critério 1: Alcohol
                    Vinho1    Vinho2
Vinho1            0.166667  0.166667
Vinho2            0.833333  0.833333

In [83]:
# critério 2
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][1], 
    key='Vinho', 
    title='Critério 2: Malic Acid'
)

df.head()

       Critério 2: Malic Acid
                       Vinho1 Vinho2
Vinho1                    0.5    0.5
Vinho2                    0.5    0.5

In [84]:
# critério 3
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][2], 
    key='Vinho', 
    title='Critério 3: Color Intensity'
)

df.head()

       Critério 3: Color Intensity
                            Vinho1 Vinho2
Vinho1                       0.125  0.125
Vinho2                       0.875  0.875

In [85]:
# critério 4
df = AHP.pretty_print_matrix(
    ahp.data['classification_matrices_normalized'][3], 
    key='Vinho', 
    title='Critério 4: Magnesium'
)

df.head()

       Critério 4: Magnesium
                      Vinho1    Vinho2
Vinho1              0.857143  0.857143
Vinho2              0.142857  0.142857

#### Matriz de preferências (de empregos por critérios)

In [86]:
# matriz de preferência: vinhos x critérios
df = pd.DataFrame(
    data=ahp.data['classification_matrices_preference'],
    index=['Vinho 1', 'Vinho 2'],
    columns=[f'C{i}' for i in range(1,len(data))]
)

df.head()

               C1   C2     C3        C4
Vinho 1  0.166667  0.5  0.125  0.857143
Vinho 2  0.833333  0.5  0.875  0.142857

#### Matriz com médias de cada critério

In [87]:
# médias de cada critério
df = pd.DataFrame(
    data=ahp.data['criteria_matrix_mean'][0],
    index=[f'C{i}' for i in range(1,len(data))],
    columns=['Média']
)

df.head()

       Média
C1  0.068037
C2  0.615731
C3  0.206547
C4  0.109685

#### Decisão final: Produto de matrizes (*matriz de preferências* $\times$ *matriz de médias de critérios*)

In [88]:
# multiplicação das duas matrizes acima
# matriz de preferência x matriz de médias de critérios
np.dot(
    ahp.data['classification_matrices_preference'],
    np.reshape(ahp.data['criteria_matrix_mean'],(-1,1))
)

array([[0.43903903],
       [0.56096097]])

# 5. **CONCLUSÃO**
Considerando o cenário em questão, bem como o problema apresentado, concluímos que o AHP se demonstoru uma solução viável, especialmente se combinado ao `Python`, garantindo flexibilidade e facilidade de execução. Ao fim, conseguimos tomar uma decisão de maneira sistemática, de acordo com o método proposto, bem como fundindo dados quantitativos com a análise de um especialista na área, instrumentalizando sua decisão de maneira metódica e escalável. Considerando o contexto em questão, escolhemos o vinho $B$, pois este apresentou 56% da média ponderada final, estando mais alinhado com as preferências do cliente, bem como aumentando a probabilidade de obter sua satisafação após o consumo do produto.